# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{scraped_resource}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["hasclass"]
  s.date = %q{2010-10-01}
  s.description = %q{TODO: longer description of your gem}
  s.email = %q{sebi.burkhard@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile"
  ]
  s.homepage = %q{http://github.com/hasclass/scraped_resource}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{TODO: one-line summary of your gem}
  s.test_files = [
    "spec/models/scraped_resource/attribute_spec.rb",
     "spec/models/scraped_resource/base_spec.rb",
     "spec/models/scraped_resource/csv/list_spec.rb",
     "spec/models/scraped_resource/excel/base_spec.rb",
     "spec/models/scraped_resource/excel/list_spec.rb",
     "spec/models/scraped_resource/excel/show_spec.rb",
     "spec/models/scraped_resource/html/list_spec.rb",
     "spec/models/scraped_resource/normalizer/base_spec.rb",
     "spec/models/scraped_resource/normalizer/numeric_spec.rb",
     "spec/models/scraped_resource/row_spec.rb",
     "spec/models/scraped_resource/util_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_runtime_dependency(%q<fastercsv>, ["= 1.5.3"])
      s.add_runtime_dependency(%q<mechanize>, ["= 1.0.0"])
      s.add_runtime_dependency(%q<roo>, ["= 1.9.3"])
      s.add_runtime_dependency(%q<google-spreadsheet-ruby>, [">= 0"])
      s.add_runtime_dependency(%q<rubyzip>, ["= 0.9.4"])
      s.add_runtime_dependency(%q<spreadsheet>, ["= 0.6.4.1"])
      s.add_development_dependency(%q<rspec>, ["= 1.3.0"])
    else
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<fastercsv>, ["= 1.5.3"])
      s.add_dependency(%q<mechanize>, ["= 1.0.0"])
      s.add_dependency(%q<roo>, ["= 1.9.3"])
      s.add_dependency(%q<google-spreadsheet-ruby>, [">= 0"])
      s.add_dependency(%q<rubyzip>, ["= 0.9.4"])
      s.add_dependency(%q<spreadsheet>, ["= 0.6.4.1"])
      s.add_dependency(%q<rspec>, ["= 1.3.0"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<fastercsv>, ["= 1.5.3"])
    s.add_dependency(%q<mechanize>, ["= 1.0.0"])
    s.add_dependency(%q<roo>, ["= 1.9.3"])
    s.add_dependency(%q<google-spreadsheet-ruby>, [">= 0"])
    s.add_dependency(%q<rubyzip>, ["= 0.9.4"])
    s.add_dependency(%q<spreadsheet>, ["= 0.6.4.1"])
    s.add_dependency(%q<rspec>, ["= 1.3.0"])
  end
end

